# Generated by Django 4.2.6 on 2023-10-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_audiofile_result_audiofile_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='title',
        ),
    ]
