# Generated by Django 4.2.6 on 2023-10-08 16:40

import authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_remove_audiofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio',
            field=models.FileField(upload_to=authorization.models.audio_upload_path),
        ),
    ]
