# Generated by Django 4.2.6 on 2023-10-08 17:15

import authorization.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0006_alter_audiofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file',
            field=models.FileField(default='path_to_default_file.mp3', upload_to=authorization.models.get_user_upload_path),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
