# Generated by Django 4.2.6 on 2023-10-08 17:20

import authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_audiofile_file_alter_audiofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio',
            field=models.FileField(upload_to=authorization.models.get_user_upload_path),
        ),
    ]
